### ISSUE TITLE
Redundant declaration of some properties?

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/stac-asset#165]
Why is it necessary to define the same property in some cases both at the class level and inside the constructor?  For instance:

https://github.com/stac-utils/stac-asset/blob/6f7f12c802234f5aaf4afa27987894b806cd29b7/src/stac_asset/http_client.py#L25

https://github.com/stac-utils/stac-asset/blob/6f7f12c802234f5aaf4afa27987894b806cd29b7/src/stac_asset/http_client.py#L42

Isn't this redundant? Could docstring be added solely to the constructor instead?

It lacks consistency; for instance, the [sas_token_endpoint](https://github.com/stac-utils/stac-asset/blob/6f7f12c802234f5aaf4afa27987894b806cd29b7/src/stac_asset/planetary_computer_client.py#L67) is only defined within a constructor for `PlanetaryComputerClient`.

**Comment by gadomski** [comment]
Thanks! I didn't understanding **sphinx-autodoc** well enough, and I thought I had to declare the docstrings on the class-level definitions. #170 should fix.
