### ISSUE TITLE
Add more allowable ContentTypes or make validation optional?

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/stac-asset#223]
https://github.com/stac-utils/stac-asset/blob/20a5d5ab8669867d3e5a7601072a501cde74e89d/src/stac_asset/validate.py#L3-L5

I was just this library out with a maxar item https://api.maxar.com/discovery/v1/catalogs/imagery/collections/wv01/items/102001008EC5AC00

But hit validation errors on the mime-types trying to download assets, which are *almost* the same. I don't think the asset type are standardized in STAC validation, but could be wrong! I thought about adding them to ALLOWABLE_PAIRS, but maybe just skipping this check altogether would be better?

```
DownloadError: ContentTypeError: the actual content type does not match the expected: actual=application/json, expected=application/geo+json
ContentTypeError: the actual content type does not match the expected: actual=application/json, expected=application/geo+json
ContentTypeError: the actual content type does not match the expected: actual=image/tiff, expected=image/tiff; application=geotiff
```

**Comment by scottyhq** [comment]
> but maybe just skipping this check altogether would be better? 

Ah, sorry after digging in the code a little bit I see that is already possible via config! 

```python
httpconfig = stac_asset.Config(http_headers={'MAXAR-API-KEY':os.environ['MAXAR_API_KEY']},
                                 http_check_content_type=False)
download_item(config=httpconfig)
```

**Comment by gadomski** [comment]
@scottyhq thanks for raising — since it's not uncommon for servers to have these media type mismatches, I wonder if switching to warn-by-default would be better UX?

**Comment by scottyhq** [comment]
> since it's not uncommon for servers to have these media type mismatches, I wonder if switching to warn-by-default would be better UX?

Sounds good to me!
